### ISSUE TITLE
Code inspector does not manage Const correctly

### ISSUE THREAD

**Issue by dankom** [retailcoder/Rubberduck#194] opened 2015-02-11 11:58 UTC
Public Const qdfCodCatasto  As String = "vbCodCatasto"

This definition is recognized by Code  inspector as implicity Variant, but the definition has String Type.
Fixing the line produces a syntax error.

**Comment by ckuhn203** [comment] 2015-02-11 12:18
@dankom  May I ask what version you're using? My co-dev believes this may already be fixed on the master branch.

**Comment by retailcoder** [comment] 2015-02-11 17:24
I cannot reproduce this behavior with build 1.1.5457.13537. However this:

    Public Const qdfCodCatasto = "vbCodCatasto"

Doesn't yield any inspection result, when it should. `VariableTypeNotDeclaredInspection` works as intended in the current [master](https://github.com/retailcoder/Rubberduck/blob/master/RetailCoder.VBE/Inspections/VariableTypeNotDeclaredInspection.cs) - this issue is considered as fixed now, stay tuned for release of [version 1.2](https://github.com/retailcoder/Rubberduck/milestones), scheduled for the end of the month: all code inspections of v1.1 have been reimplemented, and several new ones are coming.

See [opened `[code-inspection]` issues under the **Version 1.2** milestone](https://github.com/retailcoder/Rubberduck/issues?q=is%3Aopen+milestone%3A%22Version+1.2%22) to follow progress.

**Closed by retailcoder** 2015-02-11 17:24 UTC
Labels: bug, code-inspections

**Comment by dankom** [comment] 2015-02-12 17:41
My Rubberduck version is1.1.5497.13430.
I think it is the latest  downloadable.

I send you a screenshot (there are 5 issues, all for typed constants 
recognized as implicitly Variant).
My environment:
Windows 7 Home Premium 64-bit
MS Access 97

I wait for the 1.2 version.
Thank you for your reply.


Il 11/02/2015 18:24, Mathieu Guindon ha scritto:

**Comment by retailcoder** [comment] 2015-02-12 17:45
:+1 Awesome! Thanks for your feedback - we haven't tested anything with Office 97, feel free to report more issues after upgrading to v1.2, thanks for your feedback!
