### ISSUE TITLE
Unhandled exception when opening VBA editor with password-protected projects

### ISSUE THREAD

**Issue by christophocles** [retailcoder/Rubberduck#311] opened 2015-03-14 21:56 UTC
Steps to repeat:
1. Open office application (excel)
2. Open file containing password-protected VBA modules
3. Attempt to open VBA editor
4. Unhandled exception occurs. Press continue.

System.Runtime.InteropServices.COMException (0x800AC471): Can't perform operation since the project is protected.

**Comment by retailcoder** [comment] 2015-03-14 22:09
This is a known issue, resolved in 1.21 (which will be released as soon as
we get the x64 installer to work as intended) - @ckuhn203 are we ready to
release 1.21 x86 now? (release notes aside)

**Comment by ckuhn203** [comment] 2015-03-14 22:17
Yeah. Sure @retailcoder. I was waiting to work the kinks out of the x64 installer so we could release both at once, but I don't see a reason why I couldn't have the x86 version out sometime today or tomorrow. 

For posterity, this is a duplicate of #289 so I'm going to close this. 

@christophocles I would recommend keeping an eye on [our news page](http://www.rubberduck-vba.com/news.html) for information about the 1.21 bug fix release.

**Closed by ckuhn203** 2015-03-14 22:17 UTC
