### ISSUE TITLE
Extract Method isn't working properly

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#268] opened 2015-02-26 18:20 UTC
Consider the following code in a regular module.

    Option Explicit

    Public Sub DoSomething()

        Dim col As New Collection
        col.Add 1
        col.Add 2
        col.Add 3

    End Sub

Select the contents

![image](https://cloud.githubusercontent.com/assets/2716800/6398475/e438df96-bdb9-11e4-9807-9a2acdbd2a87.png)

While highlighted, select `Extract Method` from the Refactorings menu.

![image](https://cloud.githubusercontent.com/assets/2716800/6398492/04aafd90-bdba-11e4-8440-2b217a84384b.png)

Use the default settings and extract a new sub.

![image](https://cloud.githubusercontent.com/assets/2716800/6398512/20d17ee0-bdba-11e4-8f43-742cc32805fc.png)

The new method is not created, nor called, and some of the existing code is lost.

![image](https://cloud.githubusercontent.com/assets/2716800/6398536/40d59136-bdba-11e4-8028-8abade153aef.png)

**Comment by retailcoder** [comment] 2015-02-26 18:23
Interesting.. it didn't occur to me that one migh select *an entire method's body* - which kinda defeats the purpose.. but still, it shouldn't be doing that. And there's another issue with the duplicate declaration there.

**Comment by ckuhn203** [comment] 2015-02-26 18:25
Same thing happens if I only select the last two lines.

    col.Add 2
    col.Add 3

![image](https://cloud.githubusercontent.com/assets/2716800/6398628/e08ef122-bdba-11e4-9585-1ee0c5a2a755.png)

**Comment by retailcoder** [comment] 2015-02-27 00:39
The issue is with detecting object variable usages; this bug also affects
identifier usage inspections. Start looking in `VariableUsageListener` and
compare parser rules being accounted for vs. what the grammar actually
picks up, there's something done wrong there.

**Comment by retailcoder** [comment] 2015-03-01 22:26
It's not. There is no issue with detecting object variable usages.

The example is a bad one, because the object `col` is not used anywhere after the selection; no real-life working code would add items to a collections and then do nothing about it.

Indeed, there's a little glitch with ensuring the "Return value" dropdown has "(none)" selected by default, and the `Dim col As New Collection` declaration shouldn't be duplicated - that's a bug.

But if the sample code above is modified to a more realistic scenario:

    Public Sub Foo()
        Dim bar As New Collection
        bar.Add "123"
        bar.Add "456"
        bar.Add "789"
        DoSomething bar
    End Sub
    
    Public Sub DoSomething(ByRef bar As Collection)
        Debug.Print bar.Count
    End Sub

Then the *Extract Method* dialog works exactly as intended, and turns the above into the below by default (selection consists of the 3 lines that add items to the collection):

    Private Function Method1() As Collection
        Dim bar As New Collection
            bar.Add "123"
            bar.Add "456"
            bar.Add "789"
        Set Method1 = bar
    End Function

    Public Sub Foo()
        Dim bar As New Collection
        Set bar = Method1()
        DoSomething bar
    End Sub
    
    Public Sub DoSomething(ByRef bar As Collection)
        Debug.Print bar.Count
    End Sub

Closing this issue as [status-bydesign], since the behavior of the *extract method* refactoring is highly dependent on the *usage* of identifiers in the method that contains the selection.

If the code doesn't work in the first place (i.e. adding items to a collection and then not doing anything with the collection object), this tool isn't intended to fix it.

**Closed by retailcoder** 2015-03-01 22:26 UTC
Labels: bug, refactorings
