### ISSUE TITLE
The Settings dialog causes the Excel crash

### ISSUE THREAD

**Issue by s3lli9** [retailcoder/Rubberduck#588] opened 2015-06-07 12:29 UTC
I took and compiled the sources of the branch "next" for testing and I have an issue with the settings window.
When I click on the "OK" button, with or without changing settings, Excel crash at the exit with the same error for the 1.3.0.1 release (*#315*).

*Windows 8.1 (64-bit) - Office 2013 (32-bit)*

**Comment by retailcoder** [comment] 2015-06-07 13:12
Hmm I can't reproduce from here. I know at one point there was an unhandled `CultureNotFoundException` that blew things up if I switched to `sv` / Swedish, that I handled by hard-coding `en-US` as a fallback.

If culture `en-US` isn't on your system this might be the cause. I have changed that to return to whatever culture it was before instead; I believe this would fix the issue... but that wouldn't be in the 1.3.0.1 build, so I need a bit more information to know exactly what is happening on your system.

Do you have exception information / stack trace?

**Comment by s3lli9** [comment] 2015-06-07 16:10
I tried with the latest changes and I still have the same error, even if I do not change the language. I only opens the settings window, and I close the window with OK, then I quit Excel.
Sorry, I have no trace, just the following message:

![screen shot 06-07-15 at 05 58 pm](https://cloud.githubusercontent.com/assets/12442244/8024764/fb64abbc-0d3e-11e5-912a-e8685a23fd61.PNG)

On another computer, I have the following message about the exception:
`System.ExcutionEngineException` on `mscorlib.dll`

**Comment by retailcoder** [comment] 2015-06-07 17:02
A stab in the dark: does it still happen if you delete the rubberduck.config file in your %appdata%/roaming/rubberduck folder?

**Comment by s3lli9** [comment] 2015-06-07 17:35
Same error when i delete rubberduck.config file.

**Comment by Hosch250** [comment] 2015-06-07 18:29
This is sort of weird, but it doesn't surprise me really.  I am to blame for this, although I haven't the slightest idea what happened.  When you click OK, it changes the settings.  Certain windows that are only created once (such as the Code Inspections Toolbar) clean themselves up, delete themselves, and are reloaded.  There is an issue with certain windows not working after this (the Code Inspections window, for sure) on my system.  It has to be with the way it closes and reloads certain windows.

**Comment by retailcoder** [comment] 2015-06-07 18:56
@hosh250 but if it still crashes regardless of whether you hit ok or cancel?

**Comment by Hosch250** [comment] 2015-06-07 19:25
@retailcoder The OP only said it crashes for OK.

**Comment by s3lli9** [comment] 2015-06-07 21:11
I found a solution:
In `App.cs` / `LoadConfig`, I added the following code just before `var displayToolbar = false;`

```
             if (_formContextMenu! = null)
             {
                 _formContextMenu.Dispose ();
             }

             if (_projectExplorerContextMenu! = null)
             {
                 _projectExplorerContextMenu.Dispose ();
             }
```

**Comment by retailcoder** [comment] 2015-06-07 21:29
Awesome @s3lli9! Feel free to make a pull request, we'll merge it in... or I'll paste that snippet in app.cs later tonight if @Hosch250 hasn't already done it. Thanks a million!

**Comment by Hosch250** [comment] 2015-06-07 22:10
@s3lli9 Thank you so much.  I just merged this, please pull the changes.

**Closed by Hosch250** 2015-06-07 22:10 UTC
Labels: bug, settings-config
