### ISSUE TITLE
Inconsistent reporting of "Variable is never used"

### ISSUE THREAD

**Issue by rossorp** [retailcoder/Rubberduck#356] opened 2015-04-01 10:38 UTC
When running the Code Inspections, I have found that it doesn't consistently report that a variable is never used - sometimes it will report a variable as never used, other times it won't. I have an ErrorLog function that contains the following code:
```vba
    Dim iFileNumber As Integer
    ' Create the error text to be logged.
    sLogMessage = sErrorLocation & ", Error " & CStr(lErrNumber) & ": " & sErrMessage
    
    iFileNumber = FreeFile()
    Open sPath & msLOG_FILENAME For Append As #iFileNumber
    
    'Output time and message to log file.
    Print #iFileNumber, Format$(Now(), "mm/dd/yy hh:mm:ss") & " " & sLogMessage
    Close #iFileNumber
```
To me, I would say that the variable `iFileNumber` is used (a number of times at that). When I run the code inspections, sometimes it reports this variable as not being used, and other times it doesn't.

![codeinspection1](https://cloud.githubusercontent.com/assets/1185919/6939197/0a5c82b4-d862-11e4-8c4f-99fc9c060fbd.png)
![codeinspection2](https://cloud.githubusercontent.com/assets/1185919/6939293/168d70e2-d863-11e4-980a-0a3b3c7ff305.png)

As can be seen in these two screenshots, the second one contains an additional two issues - for "Variable 'iFileNumber' is never used" (two because I have similar code in another function). I did nothing to the code between taking these screenshots - all I did was press the refresh button in the Code Inspections window. After pressing the refresh button another three times I got the same code inspection results as in the first image.

This appears to be not very consistent in terms of reporting issues with the code.

System details: Windows 7 (64-bit), with Excel 2010 (32-bit) running Rubberduck 1.22.55668.31692 (32-bit)

**Comment by ckuhn203** [comment] 2015-04-01 11:22
Possible duplicate of #282 and #260. We've been struggling with this one. @retailcoder has been working on an improved grammar and parser for the next major release.

**Comment by retailcoder** [comment] 2015-04-01 12:01
That's a new one... and a scary one at that. I'll keep an eye on it, but the identifier usage inspector no longer exists in my build, replaced with much simpler code, although I'm seeing the false positives... #ParsingIsHard #GrammarIsFun

**Comment by retailcoder** [comment] 2015-04-04 06:39
The reason for this is in the grammar itself: `#iFileNumber` does not get picked up as an `ambiguousIdentifier`, but as a `literal` (more specifically, a `FILENUMBER` token).

I have modified the grammar and regenerated the parser. I introduced a `fileNumber` grammar rule:

    fileNumber : '#' (ambiguousIdentifier | literal);

And modified the relevant grammar rules to reference this `fileNumber` rule:

    openStmt : 
	OPEN WS valueStmt WS FOR WS (APPEND | BINARY | INPUT | OUTPUT | RANDOM) 
	(WS ACCESS WS (READ | WRITE | READ_WRITE))?
	(WS (SHARED | LOCK_READ | LOCK_WRITE | LOCK_READ_WRITE))?
	WS AS WS fileNumber
	(WS LEN WS? EQ WS? valueStmt)?
    ;

The good news is that it correctly picks this up:

    Dim fn As Byte
    fn = FreeFile ' assignment picked up

    Open "abc.txt" For Output As #fn 
    Close

However for some reason (seriously, that one is beyond me), this doensn't get picked up:

    Sub foo()
        Dim iFileNumber As Byte
        iFileNumber = FreeFile
        Open "abc.txt" For Output As #iFileNumber
        Write #iFileNumber, "test"
        Close
    End Sub

I tried various identifiers - some work, some don't. I have no explanation for this behavior, but it's definitely related to the parser, and it's completely ridiculous - this works as expected:

    Sub foo()
        Dim fileNumber As Byte
        fileNumber = FreeFile
        Open "abc.txt" For Output As #fileNumber
        Write #fileNumber, "test"
        Close
    End Sub

If anyone has an explanation for that one, I'm eager to hear it.

**Comment by retailcoder** [comment] 2015-04-04 06:59
Oh damn.

`#iFileNumber` fails because the parser thinks it's an `#If` conditional compilation statement. Simple as that. I'm changing the `MACRO_IF` tokens to include an obligatory whitespace *as part of the token* - it's a hack really, but I don't see another way.

**Closed** 2015-04-04 07:08 UTC
Labels: bug, code-inspections, code-parsing
