### ISSUE TITLE
Code Explorer does not list all module members when module options are not specified first in that module, or when code uses numbered lines.

### ISSUE THREAD

**Issue by PetLahev** [retailcoder/Rubberduck#286] opened 2015-03-04 22:36 UTC
Version: 1.2
Priority: Medium

There is some issue with the **Code Explorer** feature. It doesn't listed all methods from classes/forms/modules.
It looks like that it always get all the private variables and **only the very first method** in each class/form/module
![code explorer not showing all methods](https://cloud.githubusercontent.com/assets/11281023/6495090/35a927f2-c2c7-11e4-837b-aba690984116.png)

**Comment by retailcoder** [comment] 2015-03-04 22:44
Woah, how did we let that one slip! @ckuhn203 I'm assigning myself, I think I broke it when I moved the tree-generation to the `TreeViewListener` class.

**Comment by ckuhn203** [comment] 2015-03-04 22:45
Regression....

**Comment by PetLahev** [comment] 2015-03-04 22:46
Hehe Right a unit test would be sufficient here :)
BTW. Guys, your test feature is just awesome. I love it

**Comment by retailcoder** [comment] 2015-03-05 07:27
Ah, I **knew** it worked. hehe... there's no regression bug at all.

The problem is with the ANTLR grammar we're using, that wants to see module options defined first:

![image](https://cloud.githubusercontent.com/assets/5751684/6500740/dbf7ab0e-c2dd-11e4-8bad-ea2258488590.png)

**A** shows my `List` class in the Code Explorer with module options (`Option Explicit`) specified *before* the declarations.

**B** shows the same `List` class in the Code Explorer, with module options `Option Explicit`) specified *after* the declarations.

This is a serious constraint. The best we can do is #18, have a code inspection that warns about module options not being specified first. Beyond that, we need to look into re-generating the lexer and parser off a modified grammar that allows module options anywhere in the declarations section.

Current parser doesn't expect module options to be specified there, so everything below them ends up in an `ErrorNode` - that explains the missing methods.

I have yet to reproduce getting only 1 method to appear. Are module options specified first in the class shown in the screenshot?

**Comment by retailcoder** [comment] 2015-03-05 07:31
I'm deferring this issue, since we're not going to regenerate a lexer/parser for another couple of releases.

**Comment by PetLahev** [comment] 2015-03-05 19:52
Hi
here is how it looks like in my case (**still showing only the first method**)

    Option Explicit
    
    '********************************************************************************
    'clsField Class
    '
    ' Purpose:  Some text here
    '           
    '           
    '
    ' Inputs:   -none-
    '
    ' Outputs:  -none-
    '
    ' Created:  01/13/2015  Premysl Lazecky
    '
    ' Modified: .
    '
    '********************************************************************************
    
    Const MODULE_NAME       As String = "clsField"
    
    Private m_Name          As String
    Private m_ColIndex      As Long
    Private m_Filter        As String
    Private m_Criteria      As Variant
    Private m_AndVal        As String
    Private m_ChangedVal    As String
    Private m_FilterName    As String
    Private m_FilterDisplay As String
    
    Public Property Let filterName(fltName As String)
    10        m_FilterName = Trim$(fltName)
    End Property
    Public Property Get filterName() As String
    10        filterName = m_FilterName
    End Property
    
    Public Property Let filterDisplayName(displayName As String)
    10        m_FilterDisplay = Trim$(displayName)
    End Property
    Public Property Get filterDisplayName() As String
    10        filterDisplayName = m_FilterDisplay
    End Property
    
    Public Property Let FieldName(colName As String)
    10        m_Name = Trim$(colName)
    End Property
     'other properties
    
![code explorer issue](https://cloud.githubusercontent.com/assets/11281023/6513146/33a21b78-c379-11e4-839d-7250693f3a6d.png)

**Comment by PetLahev** [comment] 2015-03-05 19:54
OK, I see now what is the issue. I use **line numbering** which causes the issue in Code Explorer 
See the same class without numbering

In this case this is **very minor** issue

![code explorer without numbering](https://cloud.githubusercontent.com/assets/11281023/6513235/ccc848b8-c379-11e4-980a-069bd24cc6fa.png)

**Comment by retailcoder** [comment] 2015-03-05 19:58
Oh wow, I would have never caught that! Tagging this issue with [grammar], as it's *definitely* a grammar issue. We'll try to make numbered lines work when we rebuilt the grammar.. eventually!

**Comment by retailcoder** [comment] 2015-03-05 19:59
(and then we can add a code inspection to recommend removing them!) ;)

**Comment by retailcoder** [comment] 2015-03-09 20:09
Version 1.3 will see a grammar rebuild. This is definitely getting fixed.

**Comment by retailcoder** [comment] 2015-03-10 04:48
This will need more testing, but if you ignore the *variable 'foo' is never used* false positive, ...it's looking good:

![image](https://cloud.githubusercontent.com/assets/5751684/6569314/9c25b7a2-c6be-11e4-8f02-2f5d0d93a92e.png)

The new grammar/lexer/parser is only in the [GrammarIsFun](https://github.com/retailcoder/Rubberduck/tree/GrammarIsFun) branch for now, but when this branch gets merged into a release build branch, this bug is done: I'm happy to close this issue :)

**Closed by retailcoder** 2015-03-10 04:48 UTC
Labels: bug, code-explorer, vba-grammar
