### ISSUE TITLE
Code Explorer does not display all methods in a module

### ISSUE THREAD

**Issue by christophocles** [retailcoder/Rubberduck#312] opened 2015-03-14 22:01 UTC
Steps to repeat:

1. Open large project with many VBA modules, each containing many subroutines and functions
2. Open Code Explorer and press refresh button
3. Code Explorer treeview displays some of the methods contained in the module, but some are missing.  On my machine, one of the modules contains 27 methods but only 3 are shown in Code Explorer.

**Comment by retailcoder** [comment] 2015-03-14 22:06
Hi! Thank you for your feedback! I believe this is a known issue, will be
resolved in 1.3 - in the mean time you can move the module options to the
top of the module to get it to work as expected. Cheers!

**Comment by ckuhn203** [comment] 2015-03-15 12:25
Duplicate of #286.

**Closed by ckuhn203** 2015-03-15 12:25 UTC
