### ISSUE TITLE
Settings warning on close with no changes made

### ISSUE THREAD

**Issue by comintern** [retailcoder/Rubberduck#366] opened 2015-04-08 14:07 UTC
Opening the Options dialog and immediately closing it without making changes prompts that "Changes to setting will take affect next time the application is started."  This implies to the user that something has been changed, better behavior would be to only prompt if any settings were altered.

Also, "affect" should be "effect", but this doesn't warrant an issue by itself.

**Comment by retailcoder** [comment] 2015-04-08 14:13
That's a known issue with the settings UI, going to be addressed for next release, promise. The whole dialog is getting a facelift :smiley: 

Closing as a dupe of #184

**Closed by retailcoder** 2015-04-08 14:13 UTC
Labels: duplicate, enhancement, settings-config, user-interface

**Comment by ckuhn203** [comment] 2015-04-08 17:17
I was wondering how long it would take someone to submit that as a bug @comintern. Thanks for calling me out. =;)-
