### ISSUE TITLE
Excel 2013 crashes and re-opens after attempting to close Excel

### ISSUE THREAD

**Issue by christophocles** [retailcoder/Rubberduck#315] opened 2015-03-14 22:23 UTC
Steps to repeat:
1. Open office application (Excel 2013 32-bit)
2. Open VBA editor
3. Close Excel application
4. After Excel is closed, the Microsoft Office error recovery dialog appears -- "Microsoft is attempting to recover your information..."
5. If you do not hit 'cancel', then excel re-opens with a blank workbook

Notes:
-Error does not occur unless the VBA editor has been opened during the session.
-Error occurs whether or not VBA editor is currently open at the time you close Excel.
-Error has not occurred with Excel 2007 32-bit (also installed on this computer)

OS: Windows 8.1 64-bit
Platform: Excel 2013 32-bit
Addin version: 1.2.5541.25883

**Comment by christophocles** [comment] 2015-03-14 23:07
If you know of a way to get debugging information from this type of error, I will post more info here.  This is happening EVERY time I close the application, if I use the VBA editor in Excel 2013.

**Comment by ckuhn203** [comment] 2015-03-14 23:15
I can confirm this also does not happen for the same version in 2010, but I have seen this happen when ending a debugging session by closing the workbook instead of stopping the debugger. I do not know of a way to get more debugging info on this, nor do I have a copy of 2013 to test on. 

It's possible that we're not shutting down the add-in properly or not disposing of a resource we should be. I suspect this is happening at a fairly high level of the application. Perhaps in `Extension`, `App`, or `RubberduckMenu`.

**Comment by christophocles** [comment] 2015-03-15 02:01
I just had a similar crash with Excel 2007.  Not exactly the same exception, but it crashed at the same point -- after closing VBA editor and then Excel.  This one only happens if you close it while the Code Editor is still parsing.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80070006): System Error &H80070006 (-2147024890).   The handle is invalid. 
   at Microsoft.Vbe.Interop._VBComponent.get_Name()
   at Rubberduck.UI.CodeExplorer.CodeExplorerDockablePresenter.<AddModuleNodesAsync>d__15.MoveNext() in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\CodeExplorerDockablePresenter.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rubberduck.UI.CodeExplorer.CodeExplorerDockablePresenter.<>c__DisplayClassd.<<AddProjectNodes>b__c>d__f.MoveNext() in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\CodeExplorerDockablePresenter.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Rubberduck
    Assembly Version: 1.2.5541.25883
    Win32 Version: 1.2.0.3
    CodeBase: file:///C:/Program%20Files%20(x86)/Rubberduck/Rubberduck/Rubberduck.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Antlr4.Runtime.net45
    Assembly Version: 4.3.0.0
    Win32 Version: 4.3.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Rubberduck/Rubberduck/Antlr4.Runtime.net45.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

**Comment by ckuhn203** [comment] 2015-03-15 02:10
That one makes sense. We can handle that I believe. It crashes because the VBProjects/Components are no longer available, but the parser is still trying to parse. Related yet separate issue.

**Comment by retailcoder** [comment] 2015-03-16 02:43
I have a solid repro on this one.

From the output window (debug/x64):

    A first chance exception of type 'Rubberduck.VBA.WalkerCancelledException' occurred in Rubberduck.dll
    A first chance exception of type 'Rubberduck.VBA.WalkerCancelledException' occurred in Rubberduck.dll
    A first chance exception of type 'Rubberduck.VBA.WalkerCancelledException' occurred in Rubberduck.dll
    The thread 0x16a8 has exited with code 259 (0x103).
    The thread 0x3e0 has exited with code 259 (0x103).
    The thread 0x104c has exited with code 259 (0x103).
    The thread 0x1754 has exited with code 259 (0x103).
    The thread 0x140c has exited with code 259 (0x103).
    The program '[3792] EXCEL.EXE' has exited with code -1073741819 (0xc0000005) 'Access violation'.

**Comment by Ryankey** [comment] 2015-04-23 20:56
Confirming that this happens in Excel and Access 2013 32-bit running on a 64-bit machine. Below is a dump that I was able to grab from C:\Users\{username}\AppData\Local\Temp. They get deleted very fast.

```
<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>6.1</WindowsNTVersion>
		<Build>7601 Service Pack 1</Build>
		<Product>(0x30): Windows 7 Professional</Product>
		<Edition>Professional</Edition>
		<BuildString>7601.18798.amd64fre.win7sp1_gdr.150316-1654</BuildString>
		<Revision>1130</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>1033</LCID>
	</OSVersionInformation>
	<ProblemSignatures>
		<EventType>APPCRASH</EventType>
		<Parameter0>EXCEL.EXE</Parameter0>
		<Parameter1>15.0.4701.1001</Parameter1>
		<Parameter2>54e30a7b</Parameter2>
		<Parameter3>clr.dll</Parameter3>
		<Parameter4>4.0.30319.18444</Parameter4>
		<Parameter5>52717e84</Parameter5>
		<Parameter6>c0000005</Parameter6>
		<Parameter7>000b6a64</Parameter7>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>6.1.7601.2.1.0.256.48</Parameter1>
		<Parameter2>1033</Parameter2>
		<Parameter22>db80</Parameter22>
		<Parameter23>db80f48904568459ee85fcd5a01bc86f</Parameter23>
		<Parameter24>3e47</Parameter24>
		<Parameter25>3e470a8ab967a5f820ae39efbc1069ee</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>37AADDA1-2047-4F84-9FAF-80F4BE3CFE6B</MID>
		<MarkerFile>103C_HP_WS_Z400 Workstation_Y53335X_0U_Q2UA020_EU_4A_I0B4Ch_SHP_VD_B786G3 v03.07_T100406_W748-1_L409_M8176_J80_7Intel_86A5_93.19_#130816_N14E41684_(VS933AV)_X_CD6_Z_2_G10DE0638_Ohp DVD A DH16AAL_DDEL4026</MarkerFile>
		<SystemManufacturer>Hewlett-Packard</SystemManufacturer>
		<SystemProductName>HP Z400 Workstation</SystemProductName>
		<BIOSVersion>786G3 v03.07</BIOSVersion>
	</SystemInformation>
</WERReportMetadata>
```

**Comment by JackDunnNZ** [comment] 2015-05-04 22:23
I'm having the same issue here, only showing up in 32 bit Excel 2013 (I have 64 bit 2013 on a different machine and it doesn't have this problem). Here's the output from the log which gives some info on the .NET error:

    <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
        <System>
            <Provider Name=".NET Runtime" /> 
            <EventID Qualifiers="0">1023</EventID> 
            <Level>2</Level> 
            <Task>0</Task> 
            <Keywords>0x80000000000000</Keywords> 
            <TimeCreated SystemTime="2015-05-04T21:52:59.000000000Z" /> 
            <EventRecordID>9732</EventRecordID> 
            <Channel>Application</Channel> 
            <Computer>JACKDUNNE298</Computer> 
            <Security /> 
        </System>
        <EventData>
            <Data>Application: EXCEL.EXE Framework Version: v4.0.30319 Description: The process was terminated due to an internal error in the .NET Runtime at IP 5F665D81 (5F580000) with exit code 80131506.</Data> 
        </EventData>
    </Event>

Please let me know if there's anything I can do to help track down the cause, I saw you don't have access to 2013 yourselves

**Comment by retailcoder** [comment] 2015-05-04 22:50
@jackdunnnz thanks! I guess the good news is that the InnoSetup installer *does* work on both 32 and 64 bit office.. this is somehow related to the parsing, probably in the code explorer presenter... which is not supposed to be parsing at startup. It needs to be narrowed down further, but the fact that it was present in 1.22 tells me it's not related to identifier resolution.. which is a good sign.

**Comment by Hosch250** [comment] 2015-05-26 20:12
This is happening in x64 Office 2016 Preview too.

**Comment by Hosch250** [comment] 2015-05-26 20:14
I found this issue, which discusses the problem: http://answers.microsoft.com/en-us/office/forum/office_2013_release-outlook/outlook-shuts-down-and-reopens/6d840fa5-8141-4f20-bcea-264a33d023c6

This also discusses the problem: http://www.slipstick.com/problems/outlook-exe-continues-running-after-you-exit-outlook/

**Comment by Hosch250** [comment] 2015-05-26 23:52
Started up again after I restarted my computer :frowning:

**Comment by Hosch250** [comment] 2015-05-27 00:29
OK, it works as long as the project doesn't parse (so you basically can't use the refactorings, code explorer, or other features that parse the project.

**Comment by Hosch250** [comment] 2015-05-27 21:20
The Code Explorer works now: https://github.com/retailcoder/Rubberduck/commit/9eb6ee98d6c5faa3959a36bbf8dccb8e255cb21d

**Comment by Hosch250** [comment] 2015-05-28 02:38
As far as I know, it works when the debugger is *not* attached, but not when the debugger *is* attached.

**Closed by Hosch250** 2015-05-28 02:38 UTC
Labels: bug
